// =============================================================================
// OpenAPI generator test - validates that docs/openapi.json stays in sync
// with the Zod-based operations registry.
// =============================================================================

import { describe, it, expect } from 'vitest';
import { resolve } from 'node:path';
import { IDENTITY_OPERATIONS, ERROR_RESPONSE_SCHEMA } from '../contexts/identity/src/openapi.js';
import { ListUsersOutputSchema } from '../contexts/identity/src/schemas/index.js';
import { PublicUserSchema } from '../contexts/identity/src/schemas/get-me.schema.js';

describe('IDENTITY_OPERATIONS registry', () => {
  it('covers every protected route (defense in depth)', () => {
    const paths = new Set(IDENTITY_OPERATIONS.map((o) => o.path));
    const protectedRoutes = [
      '/v1/users/me',
      '/v1/users',
      '/v1/users/{userId}',
      '/v1/users/{userId}/activate',
      '/v1/users/{userId}/deactivate',
    ];
    for (const route of protectedRoutes) {
      expect(paths.has(route), `missing operation for ${route}`).toBe(true);
    }
  });

  it('covers every public route (auth/register, auth/login)', () => {
    const publicRoutes = ['/v1/auth/register', '/v1/auth/login'];
    for (const route of publicRoutes) {
      const op = IDENTITY_OPERATIONS.find((o) => o.path === route);
      expect(op, `missing operation for ${route}`).toBeDefined();
      expect(op!.security).toBe('none');
    }
  });

  it('has unique operationIds', () => {
    const ids = IDENTITY_OPERATIONS.map((o) => o.operationId);
    expect(new Set(ids).size, 'operationIds must be unique').toBe(ids.length);
  });

  it('uses verb in past-tense for write operations', () => {
    const writeOperations = IDENTITY_OPERATIONS.filter((o) =>
      ['POST', 'PUT', 'PATCH', 'DELETE'].includes(o.method),
    );
    for (const op of writeOperations) {
      expect(
        op.summary.toLowerCase().includes('update') ||
          op.summary.toLowerCase().includes('change') ||
          op.summary.toLowerCase().includes('activate') ||
          op.summary.toLowerCase().includes('deactivate') ||
          op.summary.toLowerCase().includes('create') ||
          op.summary.toLowerCase().includes('register') ||
          op.summary.toLowerCase().includes('login') ||
          op.summary.toLowerCase().includes('auth'),
        `${op.operationId} summary should describe the write operation: "${op.summary}"`,
      ).toBe(true);
    }
  });
});

describe('docs/openapi.json artifact', () => {
  it('is valid JSON (regenerated by `npm run generate:openapi`)', async () => {
    const { existsSync, readFileSync } = await import('node:fs');
    const path = resolve(process.cwd(), 'docs/openapi.json');
    expect(
      existsSync(path),
      'docs/openapi.json missing — run `npm run generate:openapi`',
    ).toBe(true);
    const text = readFileSync(path, 'utf8');
    const json = JSON.parse(text) as { openapi: string; paths: Record<string, unknown> };
    expect(json.openapi).toBe('3.1.0');
    expect(Object.keys(json.paths).length).toBeGreaterThan(0);
  });
});

describe('generator internals (branch coverage)', () => {
  it('ERROR_RESPONSE_SCHEMA is a Zod object with the expected envelope fields', () => {
    // exercises the ERROR_RESPONSE_SCHEMA branch used in every 4xx/5xx response
    const parsed = ERROR_RESPONSE_SCHEMA.parse({
      success: false,
      error: {
        code: 'validation.invalid_email',
        message: 'invalid email',
        details: [{ code: 'validation.invalid_format', path: 'email' }],
      },
      meta: { requestId: 'req-123', timestamp: new Date().toISOString() },
    });
    expect(parsed.success).toBe(false);
    if (parsed.success === false) {
      expect(parsed.error.code).toBe('validation.invalid_email');
    }
  });

  it('ListUsersOutputSchema parses a valid paginated response', () => {
    // exercises the ListUsersOutputSchema branch (admin endpoint)
    const payload = ListUsersOutputSchema.parse({
      users: [
        {
          id: '11111111-1111-4111-8111-111111111111',
          email: 'a@b.com',
          fullName: 'Ada',
          age: 36,
          role: 'admin',
          active: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      ],
      nextCursor: null,
    });
    expect(payload.users).toHaveLength(1);
  });

  it('PublicUserSchema accepts null age (per docs/SDD)', () => {
    // exercises the nullable age branch
    const payload = PublicUserSchema.parse({
      id: '11111111-1111-4111-8111-111111111111',
      email: 'a@b.com',
      fullName: 'Ada',
      age: null,
      role: 'admin',
      active: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
    expect(payload.age).toBeNull();
  });

  it('IDENTITY_OPERATIONS exercise every response status code (auth/admin/self)', () => {
    // Snapshot the response schema names referenced; this catches
    // typos when adding new operations.
    const referencedSchemas = new Set<string>();
    for (const op of IDENTITY_OPERATIONS) {
      // auth + admin + self operations cover all security levels
      expect(['none', 'bearer', 'admin']).toContain(op.security);
      for (const r of op.responses) {
        referencedSchemas.add(r.constructor.name);
      }
    }
    expect(referencedSchemas.size).toBeGreaterThan(0);
  });
});
