// =============================================================================
// OpenAPI generator test - validates that docs/openapi.json stays in sync
// with the Zod-based operations registry.
// =============================================================================

import { describe, it, expect } from 'vitest';
import { resolve } from 'node:path';
import { IDENTITY_OPERATIONS, ERROR_RESPONSE_SCHEMA } from '../contexts/identity/src/openapi.js';
import { ListUsersOutputSchema } from '../contexts/identity/src/schemas/index.js';
import { PublicUserSchema } from '../contexts/identity/src/schemas/get-me.schema.js';
import { buildDoc, jsonSchemaFor } from './generate-openapi.js';

describe('IDENTITY_OPERATIONS registry', () => {
  it('covers every protected route (defense in depth)', () => {
    const paths = new Set(IDENTITY_OPERATIONS.map((o) => o.path));
    const protectedRoutes = [
      '/v1/users/me',
      '/v1/users',
      '/v1/users/{userId}',
      '/v1/users/{userId}/activate',
      '/v1/users/{userId}/deactivate',
    ];
    for (const route of protectedRoutes) {
      expect(paths.has(route), `missing operation for ${route}`).toBe(true);
    }
  });

  it('covers every public route (auth/register, auth/login)', () => {
    const publicRoutes = ['/v1/auth/register', '/v1/auth/login'];
    for (const route of publicRoutes) {
      const op = IDENTITY_OPERATIONS.find((o) => o.path === route);
      expect(op, `missing operation for ${route}`).toBeDefined();
      expect(op!.security).toBe('none');
    }
  });

  it('has unique operationIds', () => {
    const ids = IDENTITY_OPERATIONS.map((o) => o.operationId);
    expect(new Set(ids).size, 'operationIds must be unique').toBe(ids.length);
  });

  it('uses verb in past-tense for write operations', () => {
    const writeOperations = IDENTITY_OPERATIONS.filter((o) =>
      ['POST', 'PUT', 'PATCH', 'DELETE'].includes(o.method),
    );
    for (const op of writeOperations) {
      expect(
        op.summary.toLowerCase().includes('update') ||
          op.summary.toLowerCase().includes('change') ||
          op.summary.toLowerCase().includes('activate') ||
          op.summary.toLowerCase().includes('deactivate') ||
          op.summary.toLowerCase().includes('create') ||
          op.summary.toLowerCase().includes('register') ||
          op.summary.toLowerCase().includes('login') ||
          op.summary.toLowerCase().includes('auth'),
        `${op.operationId} summary should describe the write operation: "${op.summary}"`,
      ).toBe(true);
    }
  });
});

describe('docs/openapi.json artifact', () => {
  it('is valid JSON (regenerated by `npm run generate:openapi`)', async () => {
    const { existsSync, readFileSync } = await import('node:fs');
    const path = resolve(process.cwd(), 'docs/openapi.json');
    expect(
      existsSync(path),
      'docs/openapi.json missing — run `npm run generate:openapi`',
    ).toBe(true);
    const text = readFileSync(path, 'utf8');
    const json = JSON.parse(text) as { openapi: string; paths: Record<string, unknown> };
    expect(json.openapi).toBe('3.1.0');
    expect(Object.keys(json.paths).length).toBeGreaterThan(0);
  });
});

describe('generator internals (branch coverage)', () => {
  it('ERROR_RESPONSE_SCHEMA is a Zod object with the expected envelope fields', () => {
    const parsed = ERROR_RESPONSE_SCHEMA.parse({
      success: false,
      error: {
        code: 'validation.invalid_email',
        message: 'invalid email',
        details: [{ code: 'validation.invalid_format', path: 'email' }],
      },
      meta: { requestId: 'req-123', timestamp: new Date().toISOString() },
    });
    expect(parsed.success).toBe(false);
    if (parsed.success === false) {
      expect(parsed.error.code).toBe('validation.invalid_email');
    }
  });

  it('ListUsersOutputSchema parses a valid paginated response', () => {
    const payload = ListUsersOutputSchema.parse({
      users: [
        {
          id: '11111111-1111-4111-8111-111111111111',
          email: 'a@b.com',
          fullName: 'Ada',
          age: 36,
          role: 'admin',
          active: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      ],
      nextCursor: null,
    });
    expect(payload.users).toHaveLength(1);
  });

  it('PublicUserSchema accepts null age (per docs/SDD)', () => {
    const payload = PublicUserSchema.parse({
      id: '11111111-1111-4111-8111-111111111111',
      email: 'a@b.com',
      fullName: 'Ada',
      age: null,
      role: 'admin',
      active: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
    expect(payload.age).toBeNull();
  });

  it('IDENTITY_OPERATIONS exercise every response status code (auth/admin/self)', () => {
    const referencedSchemas = new Set<string>();
    for (const op of IDENTITY_OPERATIONS) {
      expect(['none', 'bearer', 'admin']).toContain(op.security);
      for (const r of op.responses) {
        referencedSchemas.add(r.constructor.name);
      }
    }
    expect(referencedSchemas.size).toBeGreaterThan(0);
  });

  it('buildDoc emits OpenAPI 3.1 with paths, operations, security, components', () => {
    const doc = buildDoc();
    expect(doc.openapi).toBe('3.1.0');
    // count operations across all paths (some paths have multiple
    // methods, e.g. /v1/users/me has GET and PATCH)
    const totalOps = Object.values(doc.paths).reduce(
      (acc, methods) => acc + Object.keys(methods).length,
      0,
    );
    expect(totalOps).toBe(IDENTITY_OPERATIONS.length);
    expect(doc.components.securitySchemes.bearerAuth.scheme).toBe('bearer');
    expect(doc.components.schemas?.ErrorResponse).toBeDefined();
  });

  it('buildDoc attaches bearerAuth to bearer + admin operations but not none', () => {
    const doc = buildDoc();
    const opById = new Map<string, ReturnType<typeof getOp>>();

    function getOp(p: string, m: string): unknown {
      const methods = doc.paths[p];
      return methods?.[m.toLowerCase()];
    }

    for (const regOp of IDENTITY_OPERATIONS) {
      const built = getOp(regOp.path, regOp.method) as { security?: unknown[] };
      expect(built).toBeDefined();
      if (regOp.security === 'none') {
        expect(built.security).toBeUndefined();
      } else {
        expect(built.security).toEqual([{ bearerAuth: [] }]);
      }
    }
  });

  it('buildDoc paths include parameters, requestBody and responses for every op', () => {
    // Exercises the parametersFor, requestBodyFor, responsesFor code paths
    // for all 9 operations across 3 security models (none/bearer/admin).
    const doc = buildDoc();
    for (const regOp of IDENTITY_OPERATIONS) {
      const built = (
        doc.paths[regOp.path] as Record<string, Record<string, unknown>>
      )[regOp.method.toLowerCase()];
      expect(built).toBeDefined();
      if (regOp.parameters && regOp.parameters.length > 0) {
        expect(Array.isArray(built.parameters)).toBe(true);
        expect((built.parameters as unknown[]).length).toBe(regOp.parameters.length);
      } else {
        expect(built.parameters).toBeUndefined();
      }
      if (regOp.requestBody) {
        expect(built.requestBody).toBeDefined();
      } else {
        expect(built.requestBody).toBeUndefined();
      }
      expect(Object.keys(built.responses as object)).toEqual(
        regOp.responses.map((r) => String(r.statusCode)).sort(),
      );
    }
  });

  it('jsonSchemaFor round-trips a simple object schema', () => {
    const { z: zns } = require('zod') as typeof import('zod');
    const out = jsonSchemaFor(zns.object({ name: zns.string() }));
    expect(out).toMatchObject({
      type: 'object',
      properties: { name: { type: 'string' } },
      required: ['name'],
    });
  });
});
