// =============================================================================
// OpenAPI generator test - validates that docs/openapi.json stays in sync
// with the Zod-based operations registry.
// =============================================================================

import { describe, it, expect } from 'vitest';
import { resolve } from 'node:path';
import { IDENTITY_OPERATIONS } from '../contexts/identity/src/openapi.js';

describe('IDENTITY_OPERATIONS registry', () => {
  it('covers every protected route (defense in depth)', () => {
    const paths = new Set(IDENTITY_OPERATIONS.map((o) => o.path));
    const protectedRoutes = [
      '/v1/users/me',
      '/v1/users',
      '/v1/users/{userId}',
      '/v1/users/{userId}/activate',
      '/v1/users/{userId}/deactivate',
    ];
    for (const route of protectedRoutes) {
      expect(paths.has(route), `missing operation for ${route}`).toBe(true);
    }
  });

  it('covers every public route (auth/register, auth/login)', () => {
    const publicRoutes = ['/v1/auth/register', '/v1/auth/login'];
    for (const route of publicRoutes) {
      const op = IDENTITY_OPERATIONS.find((o) => o.path === route);
      expect(op, `missing operation for ${route}`).toBeDefined();
      expect(op!.security).toBe('none');
    }
  });

  it('has unique operationIds', () => {
    const ids = IDENTITY_OPERATIONS.map((o) => o.operationId);
    expect(new Set(ids).size, 'operationIds must be unique').toBe(ids.length);
  });

  it('uses verb in past-tense for write operations', () => {
    const writeOperations = IDENTITY_OPERATIONS.filter((o) =>
      ['POST', 'PUT', 'PATCH', 'DELETE'].includes(o.method),
    );
    for (const op of writeOperations) {
      expect(
        op.summary.toLowerCase().includes('update') ||
          op.summary.toLowerCase().includes('change') ||
          op.summary.toLowerCase().includes('activate') ||
          op.summary.toLowerCase().includes('deactivate') ||
          op.summary.toLowerCase().includes('create') ||
          op.summary.toLowerCase().includes('register') ||
          op.summary.toLowerCase().includes('login') ||
          op.summary.toLowerCase().includes('auth'),
        `${op.operationId} summary should describe the write operation: "${op.summary}"`,
      ).toBe(true);
    }
  });
});

describe('docs/openapi.json artifact', () => {
  it('is valid JSON (regenerated by `npm run generate:openapi`)', async () => {
    const { existsSync, readFileSync } = await import('node:fs');
    const path = resolve(process.cwd(), 'docs/openapi.json');
    expect(
      existsSync(path),
      'docs/openapi.json missing — run `npm run generate:openapi`',
    ).toBe(true);
    const text = readFileSync(path, 'utf8');
    const json = JSON.parse(text) as { openapi: string; paths: Record<string, unknown> };
    expect(json.openapi).toBe('3.1.0');
    expect(Object.keys(json.paths).length).toBeGreaterThan(0);
  });
});
