name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options: [dev, staging, prod]
        default: dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-node-js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: setup-aws-sam-cli
        uses: aws-actions/setup-sam@v2

      - name: install-dependencies
        run: npm ci

      - name: build-shared-workspace
        run: npm run build:shared

      - name: build-lambda-layers
        run: npm run layer:build:all

      - name: sam-build
        run: sam build --use-container

      - name: sam-deploy
        run: >
          sam deploy
          --config-env ${{ inputs.environment }}
          --no-fail-on-empty-changeset
          --no-disable-rollback